### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by sanchez496** [sanchez496/What-s-Happening#4]
We need to track down APIs to help find the following information.

News (local)
Weather (local)
Twitter (todays top hashtags)
Food (rate restaurants) 
Events (music related...?)

**Comment by sanchez496** [comment]
bands is town is not working out, eventful may be another option.

**Comment by MikeEmpire** [comment]
Got the API's for events and weather depending on the subject. The events are music related using the eventful API and the weather api is provided by simpleweather.js
